[package]
name = "monito-cli"
version = "0.2.0"
authors = ["Mizuiro Lau"]
edition = "2024"

[dependencies]
clap ={ version = "*", features = ["derive", "default"] }
monito-lib ={ path = "../monito-lib" }
log ={ workspace = true }
env_logger ={ workspace = true }