name: Tauri Build with Deno

on:
  push:
    branches:
      - main  # 可按需修改为主分支名称

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]  # 64 位和 32 位目标平台

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x  # 可根据需要指定具体版本

      - name: Install Tauri CLI with Deno
        working-directory: ./monito-gui
        run: deno install

      - name: Build Tauri app
        working-directory: ./monito-gui
        run: |
          $env:PATH = "$env:USERPROFILE/.deno/bin;$env:PATH"
          deno task tauri build --target ${{ matrix.target }}

      - name: Package artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: monito-gui-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/bundle/nsis/**